apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # repoURL: 'https://charts.bitnami.com/bitnami'
    repoURL: "https://raw.githubusercontent.com/bitnami/charts/index/bitnami"
    chart: minio
    targetRevision: 17.0.9
    helm:
      values: |
        mode: distributed
        auth:
          rootUser: admin
          rootPassword: password
        disableWebUI: true
        statefulset:
          replicaCount: 1
          zones: 1
          drivesPerNode: 4
        persistence:
          enabled: true
          size: 4Gi
        volumePermissions:
          enabled: true
        console:
          registry: docker.io
          repository: bitnami/minio-object-browser
          tag: 2.0.2-debian-12-r0
          pullPolicy: "IfNotPresent"
          replicaCount: 1
          containerPorts:
              http: 9090
          extraContainerPorts:
            - name: http
              containerPort: 9090
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
          resources:
            requests:
              cpu: 0.4
              memory: 256Mi
            limits:
              cpu: 0.8
              memory: 512Mi
          ingress:
            enabled: true
            ingressClassName: system-ingress
            hostname: minio.k3s.local
            path: /
            pathType: Prefix
            tls: true
            tlsSecretName: minio-console-tls
            annotations:
              cert-manager.io/cluster-issuer: dev-ca-issuer
              cert-manager.io/common-name: minio.k3s.local
              cert-manager.io/subject-organizations: home dev lab
              cert-manager.io/subject-countries: RU
              cert-manager.io/subject-localities: Ramenskoye
              cert-manager.io/duration: 9125h
              cert-manager.io/renew-before: 360h
              cert-manager.io/usages: server auth
              cert-manager.io/private-key-algorithm: RSA
              cert-manager.io/private-key-encoding: PKCS8
              cert-manager.io/private-key-size: "4096"
              cert-manager.io/private-key-rotation-policy: Always

  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
