---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis
  namespace: redis
spec:
  # repo: "https://charts.bitnami.com/bitnami"
  repo: "https://raw.githubusercontent.com/bitnami/charts/index/bitnami"
  chart: redis
  version: 21.2.5
  targetNamespace: redis
  valuesContent: |-
    global:
      redis:
        password: 'qUwTt8g9it'
    pdb:
      create: true
    replica:
      replicaCount: 1
